name: 'teste'
description: 'Frontend of Kerosene'
publish_to: 'none'
version: '1.0.0+1'

environment:
  sdk: '^3.9.2'

dependencies:
  bip39_mnemonic: ^4.0.1
  blockchain_utils: ^1.0.0
  qr_flutter: ^4.1.0
  http: ^1.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  timeago: ^3.5.0
  intl: ^0.18.0
  device_info_plus: ^9.1.1
  crypto: ^3.0.3

  cupertino_icons: '^1.0.8'
  bip39: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '^5.0.0'

flutter:
  uses-material-design: true

  assets:
    - 'assets/kerosenelogo.png'
    - 'assets/dollar.png'
    - 'assets/mining.png'
    - 'assets/receive.png'
    - 'assets/settings.png'
    - 'assets/send.png'
    - 'assets/dollarwhite.png'
    - 'assets/settingswhite.png'
    - 'assets/sendwhite.png'
    - 'assets/miningwhite.png'
    - 'assets/receivewhite.png'
    - 'assets/bitcoin.png'
    - 'assets/contactlesswhite.png'
    - 'assets/exportwhite.png'
    - 'assets/cadeadowhite.png'
    - 'assets/userwhite.png'
    - 'assets/voltarwhite.png'
    - 'assets/seguirwhite.png'
    - 'assets/cadeadoverify.png'
    - 'assets/presentationimage.png'
  fonts:
    - family: "Lato"
      fonts:
        - asset: "assets/fonts/Lato-Black.ttf"
        - asset: "assets/fonts/Lato-BlackItalic.ttf"
        - asset: "assets/fonts/Lato-Bold.ttf"
        - asset: "assets/fonts/Lato-BoldItalic.ttf"
        - asset: "assets/fonts/Lato-Italic.ttf"
        - asset: "assets/fonts/Lato-Light.ttf"
        - asset: "assets/fonts/Lato-LightItalic.ttf"
        - asset: "assets/fonts/Lato-Regular.ttf"
        - asset: "assets/fonts/Lato-Thin.ttf"
        - asset: "assets/fonts/Lato-ThinItalic.ttf"

    - family: "SFProDisplay"
      fonts:
        - asset: "assets/fonts/SFPRODISPLAYBLACKITALIC.OTF"
        - asset: "assets/fonts/SFPRODISPLAYBOLD.OTF"
        - asset: "assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF"
        - asset: "assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF"
        - asset: "assets/fonts/SFPRODISPLAYMEDIUM.OTF"
        - asset: "assets/fonts/SFPRODISPLAYREGULAR.OTF"
        - asset: "assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF"
        - asset: "assets/fonts/SFPRODISPLAYTHINITALIC.OTF"
        - asset: "assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF"

    - family: "HubotSans"
      fonts:
        - asset: "assets/fonts/HubotSans-Black.ttf"
        - asset: "assets/fonts/HubotSans-BlackItalic.ttf"
        - asset: "assets/fonts/HubotSans-Bold.ttf"
        - asset: "assets/fonts/HubotSans-BoldItalic.ttf"
        - asset: "assets/fonts/HubotSans-ExtraBold.ttf"
        - asset: "assets/fonts/HubotSans-ExtraBoldItalic.ttf"
        - asset: "assets/fonts/HubotSans-ExtraLight.ttf"
        - asset: "assets/fonts/HubotSans-ExtraLightItalic.ttf"
        - asset: "assets/fonts/HubotSans-Italic.ttf"
        - asset: "assets/fonts/HubotSans-Light.ttf"
        - asset: "assets/fonts/HubotSans-LightItalic.ttf"
        - asset: "assets/fonts/HubotSans-Medium.ttf"
        - asset: "assets/fonts/HubotSans-MediumItalic.ttf"
        - asset: "assets/fonts/HubotSans-Regular.ttf"
        - asset: "assets/fonts/HubotSans-SemiBold.ttf"
        - asset: "assets/fonts/HubotSans-SemiBoldItalic.ttf"

    - family: "HubotSansCondensed"
      fonts:
        - asset: "assets/fonts/HubotSans_Condensed-Black.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-BlackItalic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-Bold.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-BoldItalic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-ExtraBold.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-ExtraBoldItalic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-ExtraLight.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-ExtraLightItalic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-Italic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-Light.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-LightItalic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-Medium.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-MediumItalic.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-Regular.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-SemiBold.ttf"
        - asset: "assets/fonts/HubotSans_Condensed-SemiBoldItalic.ttf"

    - family: "HubotSansExpanded"
      fonts:
        - asset: "assets/fonts/HubotSans_Expanded-Black.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-BlackItalic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-Bold.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-BoldItalic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-ExtraBold.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-ExtraBoldItalic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-ExtraLight.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-ExtraLightItalic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-Italic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-Light.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-LightItalic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-Medium.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-MediumItalic.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-Regular.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-SemiBold.ttf"
        - asset: "assets/fonts/HubotSans_Expanded-SemiBoldItalic.ttf"

    - family: "HubotSansSemiCondensed"
      fonts:
        - asset: "assets/fonts/HubotSans_SemiCondensed-Black.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-BlackItalic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-Bold.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-BoldItalic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-ExtraBold.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-ExtraBoldItalic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-ExtraLight.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-ExtraLightItalic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-Italic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-Light.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-LightItalic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-Medium.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-MediumItalic.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-Regular.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-SemiBold.ttf"
        - asset: "assets/fonts/HubotSans_SemiCondensed-SemiBoldItalic.ttf"
