name: Deploy Kerosene API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 1. Build do JAR
      - name: Build JAR
        run: |
          cd backend/kerosene
          ./gradlew bootJar -x test

      # 2. Build + Push Docker
      - name: Build and Push image
        run: |
          IMAGE_URI=912194031318.dkr.ecr.us-east-2.amazonaws.com/kerosene:latest
          cd backend/kerosene
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # 3. Preparar chave SSH
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      # 4. Deploy na EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker login -u AWS -p $(aws ecr get-login-password --region us-east-2) 912194031318.dkr.ecr.us-east-2.amazonaws.com

            sudo docker pull 912194031318.dkr.ecr.us-east-2.amazonaws.com/kerosene:latest

            sudo docker stop api || true
            sudo docker rm api || true

            sudo docker run -d --name api -p 80:8080 \
              -e JWT_SECRET=$(aws secretsmanager get-secret-value --secret-id SECRETS-YoZDbw --query SecretString --output text) \
              -e AES_SECRET=$(aws secretsmanager get-secret-value --secret-id secret2-rhPOhC --query SecretString --output text) \
              912194031318.dkr.ecr.us-east-2.amazonaws.com/kerosene:latest
          EOF
